### ISSUE TITLE
Android AEP SDK SQliteDatabase error on Android Q (api level 29)

### ISSUE THREAD

**Issue by randomaspirer** [Adobe-Marketing-Cloud/acp-sdks#178]
We are not able to register pushidentifier on Adobe campaign for android devices running on Android Q api level 29, we are able to register fine with android devices running prior to Android Q api level 29.

Below is part of log for the errors that i see only on Android Q api level 29.

`2019-07-19 11:14:57.041 22866-23961/"packageName" E/SQLiteLog: (1) near "null": syntax error
2019-07-19 11:14:57.042 22866-23961/"packageName" E/SQLiteDatabase: Error inserting 
    android.database.sqlite.SQLiteException: near "null": syntax error (code 1 SQLITE_ERROR): , while compiling: INSERT INTO HITS(null) VALUES (NULL)
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:986)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:593)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:61)
        at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:33)
        at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1597)
        at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1468)
        at com.adobe.marketing.mobile.AndroidDatabase.insert(AndroidDatabase.java:159)
        at com.adobe.marketing.mobile.HitQueue.queue(HitQueue.java:166)
        at com.adobe.marketing.mobile.AnalyticsHitsDatabase.queue(AnalyticsHitsDatabase.java:251)
        at com.adobe.marketing.mobile.AnalyticsExtension.handleLifecycleRequestEvent(AnalyticsExtension.java:1248)
        at com.adobe.marketing.mobile.AnalyticsListenerLifecycleRequestContent$1.run(AnalyticsListenerLifecycleRequestContent.java:44)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
2019-07-19 11:14:57.042 22866-23961/"packageName" E/AdobeExperienceSDK: HitQueue - A database error occurred preventing a hit from being inserted
2019-07-19 11:14:57.042 22866-23961/"packageName" E/AdobeExperienceSDK: HitsDatabase - Database in unrecoverable state, resetting.`

**Dependencies used:**
implementation 'com.adobe.marketing.mobile:analytics:1.1.1'
implementation 'com.adobe.marketing.mobile:campaign:1.0.1'
implementation 'com.adobe.marketing.mobile:userprofile:1.0.1'
implementation 'com.adobe.marketing.mobile:sdk-core:1.3.1' even tried the 1.4.1 same error.

**Comment by PravinPK** [comment]
Hi @randomaspirer,
 
Thanks for reporting. We are working on the fix and I will update the ticket once we have more information.

Thank you,
Pravin
Mobile Engineer
[Adobe Experience Cloud](http://www.adobe.com/experience-cloud.html)

**Comment by randomaspirer** [comment]
Hi PravinPk,

Any update on this yet?

**Comment by PravinPK** [comment]
Hi @randomaspirer,
Thanks for your patience. The issue is fixed and will be available on the upcoming AndroidCore release version 1.4.3 happening on August 15th.

Thanks,
Pravin
Mobile Engineer
Adobe Experience Cloud

**Comment by randomaspirer** [comment]
Pravin,

Cool once its out there will test it and let you know if the actual problem of not being able to register Push identifier on api level 29 is resolved or not.

**Comment by shalehaha** [comment]
@raducotescu 
The version 1.4.3 is out, please verify it when you get a chance. Thanks.
