### ISSUE TITLE
android - NonSdkApiUsedViolation 

### ISSUE THREAD

**Issue by musilto7** [Adobe-Marketing-Cloud/acp-sdks#360]
Hello,
I have your sdk integrated in my project

 // ADOBE
    implementation 'com.adobe.marketing.mobile:core:1.5.0'
    implementation 'com.adobe.marketing.mobile:identity:1.2.0'
    implementation 'com.adobe.marketing.mobile:analytics:1.2.3'
    implementation 'com.adobe.marketing.mobile:userprofile:1.0.1'
    implementation 'com.adobe.marketing.mobile:lifecycle:1.0.2'
    implementation 'com.adobe.marketing.mobile:signal:1.0.2'

But when the app is uploaded to the the google play, following warning is shown: 

StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Ljava/net/Socket;->impl:Ljava/net/SocketImpl;

         at android.os.StrictMode.lambda$static$1(StrictMode.java:428)

         at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)

         at java.lang.Class.getDeclaredField(Native Method)

         at com.google.android.gms.org.conscrypt.Platform.getFileDescriptor(:com.google.android.gms@200414028@20.04.14 (100400-294335909):1)

         at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(:com.google.android.gms@200414028@20.04.14 (100400-294335909):7)

         at com.android.okhttp.okio.Okio$2.read(Okio.java:136)

         at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)

         at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)

         at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)

         at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)

         at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)

         at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)

         at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737)

         at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:609)

         at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:471)

         at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)

         at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538)

         at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)

         at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:26)

         at com.adobe.marketing.mobile.AndroidHttpConnection.h(:1)

         at com.adobe.marketing.mobile.AnalyticsHitsDatabase.a(:77)

         at com.adobe.marketing.mobile.AnalyticsHitsDatabase.a(:16)

         at com.adobe.marketing.mobile.AnalyticsHitsDatabase.a(:1)

         at com.adobe.marketing.mobile.HitQueue$1.run(:5)

         at java.lang.Thread.run(Thread.java:764)

**Comment by shalehaha** [comment]
@musilto7 

The SDK doesn't directly use any okhttp method, it only relies on Android's API.  Does your project depend on okhttp lib? I found https://github.com/square/okhttp/issues/3980. 

Let us know if that if helpful.

Jiabin
