### ISSUE TITLE
Adobe Media Analytics : NPE on trackSessionStart()

### ISSUE THREAD

**Issue by nishantkp** [Adobe-Marketing-Cloud/acp-sdks#403]
Hi,

When I start media session with `MediaTracker.trackSessionStart(mediaInfo, customMap);`, app crashes with 
```java
java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
        at java.util.regex.Matcher.reset(Matcher.java:177)
        at java.util.regex.Matcher.<init>(Matcher.java:90)
        at java.util.regex.Pattern.matcher(Pattern.java:297)
        at com.adobe.marketing.mobile.MediaReportHelper.extractSessionID(MediaReportHelper.java:300)
        at com.adobe.marketing.mobile.MediaSession$1.run(MediaSession.java:204)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
```
At first I am creating MediaTracker with `Media.createTracker()` and then I am using `MediaTracker.trackSessionStart(data,data);`

Not sure what is wrong with the setup.

**Comment by rymorale** [comment]
Thanks for the report @nishantkp. What version of the Media Analytics SDK are you using? Could we also get a full log of the crash?

Thanks,
Ryan Morales
Mobile Engineer
[Adobe Experience Cloud](https://www.adobe.com/experience-cloud.html)

**Comment by cacheung** [comment]
@nishantkp 
Can you set the log level to MobileCore.setLogLevel(LoggingMode.VERBOSE);
And send us the full log?

Thanks,
Calise Cheung
Mobile Engineer

**Comment by nishantkp** [comment]
Hi Ryan & Calise,

Media analytics SDK version is 2.0.0.

Will it be helpful or you will be needing full bugreport?
 
```java
2020-06-25 14:51:51.171 3557-3589/com.shawmedia.smglobal V/AdobeExperienceSDK: EventHub(AMSEventHub) - Event (87a2a918-8e4c-4b89-89bc-660582f287fb) #26 (Media::CreateTrackerRequest) resulted in 0 consequence events. Time in rules was 0 milliseconds.
2020-06-25 14:51:51.173 3557-3589/com.shawmedia.smglobal V/AdobeExperienceSDK: EventBus(EventHub) - Processing event #26: {
        class: Event,
        name: Media::CreateTrackerRequest,
        eventNumber: 26,
        uniqueIdentifier: 87a2a918-8e4c-4b89-89bc-660582f287fb,
        source: com.adobe.eventsource.media.requesttracker,
        type: com.adobe.eventtype.media,
        pairId: null,
        responsePairId: dc116fc9-660f-402a-b321-edf44e942357,
        timestamp: 1593111111170,
        data: {
            "event.param" : { },
            "trackerid" : "d73f88d1-986e-4e7a-ad2d-fa6200b8f161"
        }
    }
2020-06-25 14:51:51.191 3557-3589/com.shawmedia.smglobal V/AdobeExperienceSDK: EventHub(AMSEventHub) - Event (1c7c4368-245a-4762-b6ab-553289e54ac5) #27 (Media::TrackMedia) resulted in 0 consequence events. Time in rules was 0 milliseconds.
2020-06-25 14:51:51.194 3557-3589/com.shawmedia.smglobal V/AdobeExperienceSDK: EventBus(EventHub) - Processing event #27: {
        class: Event,
        name: Media::TrackMedia,
        eventNumber: 27,
        uniqueIdentifier: 1c7c4368-245a-4762-b6ab-553289e54ac5,
        source: com.adobe.eventsource.media.trackmedia,
        type: com.adobe.eventtype.media,
        pairId: null,
        responsePairId: 9cdb4d63-8bb1-4706-8584-cb7308ec1031,
        timestamp: 1593111111190,
        data: {
            "event.timestamp" : 1593111111189,
            "event.metadata" : {
                "video.episode-id" : "5610521",
                "video.channel" : "global",
                "a.media.show" : "The Late Show with Stephen Colbert",
                "video.type" : "episode",
                "a.media.episode" : "",
                "a.media.season" : "",
                "auth.status" : "non-authenticated"
            },
            "event.param" : {
                "media.name" : "global;The Late Show with Stephen Colbert;unavailable;Jun/19/2020;unavailable;",
                "media.type" : "video",
                "media.length" : 2453.7919921875,
                "media.resumed" : false,
                "media.id" : "GLOB0056105210000000",
                "media.streamtype" : "vod",
                "media.prerollwaitingtime" : 250
            },
            "event.internal" : false,
            "sessionid" : "97900b7b-191c-4c7f-938d-b25b96031f8d",
            "event.name" : "sessionstart",
            "trackerid" : "d73f88d1-986e-4e7a-ad2d-fa6200b8f161"
        }
    }
2020-06-25 14:51:51.197 3557-3589/com.shawmedia.smglobal V/AdobeExperienceSDK: EventHub(AMSEventHub) - Event (8acaf200-531a-48e9-9272-2b2771854af9) #28 (Media::TrackMedia) resulted in 0 consequence events. Time in rules was 0 milliseconds.
2020-06-25 14:51:51.198 3557-3624/com.shawmedia.smglobal D/AdobeExperienceSDK: MediaCollectionTracker - cleanMetadata - Dropping metadata entry key:video.episode-id value:5610521. Key should contain only alphabets, digits, '_' and '.'.
2020-06-25 14:51:51.199 3557-3589/com.shawmedia.smglobal V/AdobeExperienceSDK: EventBus(EventHub) - Processing event #28: {
        class: Event,
        name: Media::TrackMedia,
        eventNumber: 28,
        uniqueIdentifier: 8acaf200-531a-48e9-9272-2b2771854af9,
        source: com.adobe.eventsource.media.trackmedia,
        type: com.adobe.eventtype.media,
        pairId: null,
        responsePairId: c81839d5-c6ce-41c0-898d-962c9ec82645,
        timestamp: 1593111111192,
        data: {
            "event.timestamp" : 1593111111191,
            "event.internal" : false,
            "sessionid" : "97900b7b-191c-4c7f-938d-b25b96031f8d",
            "event.name" : "bufferstart",
            "trackerid" : "d73f88d1-986e-4e7a-ad2d-fa6200b8f161"
        }
    }
2020-06-25 14:51:51.201 3557-3589/com.shawmedia.smglobal V/AdobeExperienceSDK: EventHub(AMSEventHub) - Event (82e3614a-824d-4650-8007-2f0e8881fc85) #29 (Media::TrackMedia) resulted in 0 consequence events. Time in rules was 0 milliseconds.
2020-06-25 14:51:51.202 3557-3589/com.shawmedia.smglobal V/AdobeExperienceSDK: EventBus(EventHub) - Processing event #29: {
        class: Event,
        name: Media::TrackMedia,
        eventNumber: 29,
        uniqueIdentifier: 82e3614a-824d-4650-8007-2f0e8881fc85,
        source: com.adobe.eventsource.media.trackmedia,
        type: com.adobe.eventtype.media,
        pairId: null,
        responsePairId: bd9494bf-b595-4281-9e2c-5a0d3c4a2a3b,
        timestamp: 1593111111192,
        data: {
            "event.timestamp" : 1593111111192,
            "event.internal" : false,
            "sessionid" : "97900b7b-191c-4c7f-938d-b25b96031f8d",
            "event.name" : "seekstart",
            "trackerid" : "d73f88d1-986e-4e7a-ad2d-fa6200b8f161"
        }
    }
2020-06-25 14:51:51.204 3557-3830/com.shawmedia.smglobal W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
2020-06-25 14:51:51.209 3557-3624/com.shawmedia.smglobal V/AdobeExperienceSDK: MediaCollectionTracker - track - Processing event - sessionstart
2020-06-25 14:51:51.211 3557-3624/com.shawmedia.smglobal V/AdobeExperienceSDK: MediaRealTimeService - startSession - Session started successfully.
2020-06-25 14:51:51.233 3557-3624/com.shawmedia.smglobal V/AdobeExperienceSDK: MediaCollectionTracker - track - Processing event - bufferstart
2020-06-25 14:51:51.235 3557-3624/com.shawmedia.smglobal V/AdobeExperienceSDK: MediaCollectionTracker - track - Processing event - seekstart
2020-06-25 14:51:51.247 3557-3830/com.shawmedia.smglobal W/VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
2020-06-25 14:51:51.266 3557-3569/com.shawmedia.smglobal I/art: Background partial concurrent mark sweep GC freed 21883(1480KB) AllocSpace objects, 9(27MB) LOS objects, 19% free, 64MB/80MB, paused 8.653ms total 141.764ms
2020-06-25 14:51:51.323 3557-3830/com.shawmedia.smglobal I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
2020-06-25 14:51:51.438 3557-3593/com.shawmedia.smglobal V/AdobeExperienceSDK: MediaSession - sendHit - Sending network hit for event sessionStart.
2020-06-25 14:51:51.439 3557-3593/com.shawmedia.smglobal D/AdobeExperienceSDK: MediaSession - sendHit - Generated url https://corus.hb.omtrdc.net/api/v1/sessions for event sessionStart
2020-06-25 14:51:51.452 3557-3851/com.shawmedia.smglobal D/AdobeExperienceSDK: HttpConnectionHandler - Connecting to URL https://corus.hb.omtrdc.net/api/v1/sessions (POST)
2020-06-25 14:51:51.483 3557-3589/com.shawmedia.smglobal V/AdobeExperienceSDK: EventHub(AMSEventHub) - Event (053fcc2b-22d1-43ee-9573-042ea785947b) #30 (Media::TrackMedia) resulted in 0 consequence events. Time in rules was 0 milliseconds.
2020-06-25 14:51:51.485 3557-3589/com.shawmedia.smglobal V/AdobeExperienceSDK: EventBus(EventHub) - Processing event #30: {
        class: Event,
        name: Media::TrackMedia,
        eventNumber: 30,
        uniqueIdentifier: 053fcc2b-22d1-43ee-9573-042ea785947b,
        source: com.adobe.eventsource.media.trackmedia,
        type: com.adobe.eventtype.media,
        pairId: null,
        responsePairId: eea9d7dd-2d35-4027-838e-87d1591e2998,
        timestamp: 1593111111482,
        data: {
            "event.timestamp" : 1593111111481,
            "event.param" : {
                "qoe.droppedframes" : 0.0,
                "qoe.fps" : 0.0,
                "qoe.startuptime" : 0.0,
                "qoe.bitrate" : 0.0
            },
            "event.internal" : false,
            "sessionid" : "97900b7b-191c-4c7f-938d-b25b96031f8d",
            "event.name" : "qoeupdate",
            "trackerid" : "d73f88d1-986e-4e7a-ad2d-fa6200b8f161"
        }
    }
2020-06-25 14:51:51.487 3557-3624/com.shawmedia.smglobal V/AdobeExperienceSDK: MediaCollectionTracker - track - Processing event - qoeupdate
2020-06-25 14:51:51.488 3557-3624/com.shawmedia.smglobal V/AdobeExperienceSDK: MediaContext - enterState - Buffer
2020-06-25 14:51:51.668 3557-3624/com.shawmedia.smglobal V/AdobeExperienceSDK: MediaSession - queueHit - Adding bufferStart hit to the queue: 
2020-06-25 14:51:51.669 3557-3624/com.shawmedia.smglobal V/AdobeExperienceSDK: MediaRuleEngine - processRule - Predicates failed for MediaRule API::trackEvent(SeekStart)
2020-06-25 14:51:51.669 3557-3624/com.shawmedia.smglobal D/AdobeExperienceSDK: MediaCollectionTracker - Media tracker is tracking buffer events, call 'API:trackEvent(BufferComplete)' first to stop tracking buffer events.
    
    --------- beginning of crash
2020-06-25 14:51:51.675 3557-3851/com.shawmedia.smglobal E/AndroidRuntime: FATAL EXCEPTION: pool-20-thread-1
    Process: com.shawmedia.smglobal, PID: 3557
    java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
        at java.util.regex.Matcher.reset(Matcher.java:995)
        at java.util.regex.Matcher.<init>(Matcher.java:174)
        at java.util.regex.Pattern.matcher(Pattern.java:1006)
        at com.adobe.marketing.mobile.MediaReportHelper.extractSessionID(MediaReportHelper.java:300)
        at com.adobe.marketing.mobile.MediaSession$1.run(MediaSession.java:204)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
2020-06-25 14:51:51.676 3557-3593/com.shawmedia.smglobal V/AdobeExperienceSDK: MediaSession - process - Waiting for the previous hit to be sent.
2020-06-25 14:51:51.832 3557-3589/com.shawmedia.smglobal V/AdobeExperienceSDK: EventHub(AMSEventHub) - Event (1bd73020-4ec8-4c92-af05-60938060a988) #31 (Media::TrackMedia) resulted in 0 consequence events. Time in rules was 0 milliseconds.
2020-06-25 14:51:51.834 3557-3589/com.shawmedia.smglobal V/AdobeExperienceSDK: EventBus(EventHub) - Processing event #31: {
        class: Event,
        name: Media::TrackMedia,
        eventNumber: 31,
        uniqueIdentifier: 1bd73020-4ec8-4c92-af05-60938060a988,
        source: com.adobe.eventsource.media.trackmedia,
        type: com.adobe.eventtype.media,
        pairId: null,
        responsePairId: 1552bab5-c21e-477c-9b51-64fad2c0173a,
        timestamp: 1593111111828,
        data: {
            "event.timestamp" : 1593111111827,
            "event.internal" : false,
            "sessionid" : "97900b7b-191c-4c7f-938d-b25b96031f8d",
            "event.name" : "bufferstart",
            "trackerid" : "d73f88d1-986e-4e7a-ad2d-fa6200b8f161"
        }
    }
2020-06-25 14:51:51.836 3557-3624/com.shawmedia.smglobal V/AdobeExperienceSDK: MediaCollectionTracker - track - Processing event - bufferstart
2020-06-25 14:51:51.838 3557-3624/com.shawmedia.smglobal V/AdobeExperienceSDK: MediaRuleEngine - processRule - Predicates failed for MediaRule API::trackEvent(BufferStart)
2020-06-25 14:51:51.838 3557-3624/com.shawmedia.smglobal D/AdobeExperienceSDK: MediaCollectionTracker - Media tracker is tracking buffer events, call 'API:trackEvent(BufferComplete)' first to stop tracking buffer events.
```

**Comment by cacheung** [comment]
Thanks @nishantkp.  Yes. Let create a bug and track there as well. Contact [Adobe Client Care](http://helpx.adobe.com/marketing-cloud/contact-support.html).

At the mean time, we will look at the log you provided.

Thanks,
Calise Cheung
Mobile Engineer

**Comment by addb** [comment]
Hi @nishantkp the URL that you are configuring is for Media Heartbeats Backend Which was supported till Media 1.X. From Media 2.0.0 we support collection API. And you need to get a Collection server URL and configure the Media Extension with that.

**Comment by nishantkp** [comment]
hi @addb , 

How do i obtain collection server url?

**Comment by addb** [comment]
Hi @nishantkp,

I just verified with the backend team. For Collection server url you just have to update `corus.hb.omtrdc.net` to `corus.hb-api.omtrdc.net`.

Also did you already file a bug with the client care?

Thanks,
Arjun

**Comment by nishantkp** [comment]
No i did not filed a bug with client care

**Comment by addb** [comment]
Ok, thats fine. Please try the collection URL and see if it works. Meanwhile we will internally track and fix the NPE for this scenario. 

Thanks,
Arjun

**Comment by nishantkp** [comment]
Hi @addb,

It seems to be sending events correctly now. Thanks a bunch for really quick solution.

**Comment by cacheung** [comment]
As discussed over email we will update this issue once we release our next version.

Thanks,
Calise

**Comment by addb** [comment]
Hi @nishantkp,

I would like to add to our conversation of using Collection server. The URL `corus.hb-api.omtrdc.net` should be used for production code. And for dev and implementation/testing purposes you can use the staging endpoint `corus-stage.hb-api.omtrdc.net`

Thanks,
Arjun
