### ISSUE TITLE
Android Crash

### ISSUE THREAD

**Issue by smithaaron** [Adobe-Marketing-Cloud/acp-sdks#441]
Our crashlytics stats are showing the following crash

```
Fatal Exception: java.lang.IllegalStateException: state: 0
       at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:183)
       at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:129)
       at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:750)
       at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:622)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
       at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:106)
       at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:30)
       at com.google.firebase.perf.network.zzf.getInputStream(zzf.java:57)
       at com.google.firebase.perf.network.zzc.getInputStream(zzc.java:11)
       at com.adobe.marketing.mobile.AndroidHttpConnection.getInputStream(AndroidHttpConnection.java:49)
       at com.adobe.marketing.mobile.AndroidHttpConnection.close(AndroidHttpConnection.java:119)
       at com.adobe.marketing.mobile.RemoteDownloader.processNetworkConnectionObject(RemoteDownloader.java:280)
       at com.adobe.marketing.mobile.RemoteDownloader.startDownloadSync(RemoteDownloader.java:267)
       at com.adobe.marketing.mobile.ConfigurationDownloader.downloadConfig(ConfigurationDownloader.java:62)
       at com.adobe.marketing.mobile.ConfigurationExtension.processConfigureWithAppIDEvent(ConfigurationExtension.java:458)
       at com.adobe.marketing.mobile.ConfigurationExtension$3.run(ConfigurationExtension.java:316)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
```

There is no mention of any source lines in our app, but we've noticed that batches of these crashes correlate to the customer receiving push notifications. We have not been able to reproduce locally.

Our setup
```
implementation 'com.adobe.marketing.mobile:griffonbridge:1.+'
    implementation 'com.adobe.marketing.mobile:analytics:1.+'
    implementation 'com.adobe.marketing.mobile:sdk-core:1.+'
```
```
private fun initAdobeAnalytics() {
        setApplication(this)
        configureWithAppID(BuildConfig.ADOBE_ANALYTICS_DASHBOARD_APP_ID)
        setLogLevel(LoggingMode.VERBOSE)
        try {
            Identity.registerExtension()
            Lifecycle.registerExtension()
            Signal.registerExtension()
            Analytics.registerExtension()
            AndroidGriffonBridge.registerExtension()
            start(null)
        } catch (e: Exception) {
            //TODO: handle exception
        }
    }
```

**Comment by cacheung** [comment]
Hi,
     We look at the crashlytics stats, crash happens from Android okhttp lib and firebase-perf is in the middle of the trace.  Most likely firebase-perf causes the crash.
     We don't think it is related to sdk.

Best Regards,
Calise Cheung
Mobile Engineer

**Comment by shalehaha** [comment]
@smithaaron This crash has been fixed in the latest build. Thanks.
