### ISSUE TITLE
Android - Assurance Error Code 4400 

### ISSUE THREAD

**Issue by rd-martin-jaeger** [Adobe-Marketing-Cloud/acp-sdks#469]
Hi there,

we have some troubles to get griffon running in our project so we can test the migration to the newest sdk version. 
Following the [setup instructions](https://aep-sdks.gitbook.io/docs/using-mobile-extensions/adobe-experience-platform-assurance) (where btw the core library name is wrong, it should be sdk-core) i'm able to start the Assurance Enter-Pin-View and to establish a websocket connection (see logs). 

Once i enter the pin, an unhandled exception will be thrown and shows a never ending loading indicator. 

Logs:
```
D/AdobeExperienceSDK: Assurance - Confirm url for pin-code entry received, attempting connection to: wss://connect.griffon.adobe.com/client/v1?sessionId=...
D/AdobeExperienceSDK: Assurance - Websocket connected.
D/AdobeExperienceSDK: Assurance - Sending client info event to Assurance
W/System.err: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/app/ActivityCompat;
W/System.err:     at com.adobe.marketing.mobile.AssuranceClientInfo.getCurrentLocationPermission(AssuranceClientInfo.java:207)
W/System.err:     at com.adobe.marketing.mobile.AssuranceClientInfo.getDeviceInfo(AssuranceClientInfo.java:96)
W/System.err:     at com.adobe.marketing.mobile.AssuranceClientInfo.getData(AssuranceClientInfo.java:58)
W/System.err:     at com.adobe.marketing.mobile.AssuranceSession.sendClientInfoEvent(AssuranceSession.java:763)
W/System.err:     at com.adobe.marketing.mobile.AssuranceSession.onSocketConnected(AssuranceSession.java:418)
W/System.err:     at com.adobe.marketing.mobile.AssuranceWebViewSocket$WebViewJavascriptInterface.onSocketOpened(AssuranceWebViewSocket.java:220)
W/System.err:     at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err:     at android.os.MessageQueue.next(MessageQueue.java:336)
W/System.err:     at android.os.Looper.loop(Looper.java:174)
W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:67)
W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.app.ActivityCompat" on path: DexPathList[[zip file "/data/app/de.some.app-_K8G5U-QC-mqI2_M1-YzwQ==/base.apk"],nativeLibraryDirectories=[/data/app/de.some.app-_K8G5U-QC-mqI2_M1-YzwQ==/lib/arm64, /data/app/de.some.app-_K8G5U-QC-mqI2_M1-YzwQ==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /system/product/lib64]]
W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
W/System.err: 	... 10 more
E/AdobeExperienceSDK: Assurance - Uncaught Error: Java exception was raised during method invocation
I/chromium: [INFO:CONSOLE(40)] "Uncaught Error: Java exception was raised during method invocation", source: file:///android_asset/WebviewSocket.html (40)
```

Versions
```
Gradle 6.7
Build time:   2020-10-14 16:13:12 UTC
Revision:     312ba9e0f4f8a02d01854d1ed743b79ed996dfd3

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          1.8.0_222 (AdoptOpenJDK 25.222-b10)
OS:           Mac OS X 10.15.7 x86_64

Android
compileSdkVersion = 29
targetSdkVersion = 29
buildToolsVersion = "30.0.2"
```

Dependencies
```
release
releaseCompileClasspath - Dependencies for compilation
+--- com.squareup.okhttp3:logging-interceptor:4.9.0@jar
+--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.4.10@jar
+--- org.jetbrains.kotlin:kotlin-android-extensions-runtime:1.4.10@jar
+--- com.jakewharton.threetenabp:threetenabp:1.3.0@aar
+--- com.google.firebase:firebase-perf:19.0.9@aar
+--- org.jetbrains.kotlin:kotlin-reflect:1.4.10@jar
+--- com.squareup.leakcanary:plumber-android:2.5@aar
+--- com.google.firebase:firebase-firestore-ktx:22.0.0@aar
+--- com.google.firebase:firebase-dynamic-links-ktx:19.1.1@aar
+--- com.google.firebase:firebase-crashlytics-ktx:17.2.2@aar
+--- com.google.firebase:firebase-common-ktx:19.3.1@aar
+--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.4.10@jar
+--- androidx.fragment:fragment-ktx:1.2.5@aar
+--- androidx.activity:activity-ktx:1.1.0@aar
+--- androidx.lifecycle:lifecycle-runtime-ktx:2.3.0-beta01@aar
+--- androidx.lifecycle:lifecycle-viewmodel-ktx:2.2.0@aar
+--- org.jetbrains.anko:anko-coroutines:0.10.8@aar
+--- io.coil-kt:coil-base:1.0.0@aar
+--- androidx.room:room-ktx:2.2.5@aar
+--- org.jetbrains.kotlinx:kotlinx-coroutines-android:1.4.0@jar
+--- org.jetbrains.kotlinx:kotlinx-coroutines-play-services:1.4.0@jar
+--- androidx.core:core-ktx:1.3.2@aar
+--- androidx.lifecycle:lifecycle-livedata-ktx:2.2.0@aar
+--- org.jetbrains.anko:anko-commons:0.10.8@aar
+--- io.github.reactivecircus.flowbinding:flowbinding-android:1.0.0-beta01@aar
+--- com.google.firebase:firebase-functions:19.1.0@aar
+--- com.google.firebase:firebase-crashlytics:17.2.2@aar
+--- com.squareup.okhttp3:okhttp:4.9.0@jar
+--- com.airbnb.android:lottie:3.4.4@aar
+--- com.squareup.moshi:moshi:1.11.0@jar
+--- com.google.firebase:firebase-firestore:22.0.0@aar
+--- io.grpc:grpc-okhttp:1.28.0@jar
+--- com.squareup.okhttp:okhttp:2.7.5@jar
+--- com.squareup.okio:okio:2.9.0@jar
+--- androidx.collection:collection-ktx:1.1.0@jar
+--- androidx.lifecycle:lifecycle-livedata-core-ktx:2.2.0@aar
+--- org.jetbrains.anko:commons-base:0.10.8@aar
+--- io.github.reactivecircus.flowbinding:flowbinding-lifecycle:1.0.0-beta01@aar
+--- io.github.reactivecircus.flowbinding:flowbinding-common:1.0.0-beta01@aar
+--- org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.4.0@jar
+--- org.jetbrains.kotlin:kotlin-stdlib:1.4.10@jar
+--- org.jetbrains.kotlin:kotlin-stdlib-common:1.4.10@jar
+--- org.jetbrains:annotations:13.0@jar
+--- com.google.android.gms:play-services-oss-licenses:17.0.0@aar
+--- com.google.android.gms:play-services-clearcut:17.0.0@aar
+--- com.google.android.gms:play-services-maps:17.0.0@aar
+--- com.google.android.gms:play-services-phenotype:17.0.0@aar
+--- com.google.android.gms:play-services-location:17.1.0@aar
+--- com.google.firebase:firebase-auth:20.0.0@aar
+--- com.google.android.gms:play-services-analytics:17.0.0@aar
+--- com.google.firebase:firebase-auth-interop:19.0.0@aar
+--- com.google.firebase:firebase-messaging:21.0.0@aar
+--- com.google.firebase:firebase-iid:21.0.0@aar
+--- com.google.firebase:firebase-iid-interop:17.0.0@aar
+--- com.google.firebase:firebase-dynamic-links:19.1.1@aar
+--- com.google.android.gms:play-services-auth-api-phone:17.4.0@aar
+--- com.google.android.gms:play-services-safetynet:17.0.0@aar
+--- com.google.android.gms:play-services-tagmanager-v4-impl:17.0.0@aar
+--- com.google.android.gms:play-services-analytics-impl:17.0.0@aar
+--- com.google.firebase:firebase-database-collection:17.0.1@aar
+--- com.google.android.gms:play-services-base:17.3.0@aar
+--- com.google.firebase:firebase-config:20.0.0@aar
+--- com.google.firebase:firebase-core:18.0.0@aar
+--- com.google.firebase:firebase-analytics:18.0.0@aar
+--- com.google.android.gms:play-services-measurement-api:18.0.0@aar
+--- com.google.firebase:firebase-installations:16.3.3@aar
+--- com.google.firebase:firebase-abt:20.0.0@aar
+--- com.google.firebase:firebase-datatransport:17.0.3@aar
+--- com.google.firebase:firebase-common:19.3.1@aar
+--- com.google.firebase:firebase-installations-interop:16.0.0@aar
+--- com.google.android.gms:play-services-cloud-messaging:16.0.0@aar
+--- com.google.android.gms:play-services-tasks:17.1.0@aar
+--- com.google.firebase:firebase-measurement-connector:18.0.0@aar
+--- com.google.android.gms:play-services-measurement:18.0.0@aar
+--- com.google.android.gms:play-services-measurement-sdk:18.0.0@aar
+--- com.google.android.gms:play-services-measurement-impl:18.0.0@aar
+--- com.google.android.gms:play-services-stats:17.0.0@aar
+--- com.google.android.gms:play-services-places-placereport:17.0.0@aar
+--- com.google.android.gms:play-services-ads-identifier:17.0.0@aar
+--- com.google.android.gms:play-services-measurement-sdk-api:18.0.0@aar
+--- com.google.android.gms:play-services-measurement-base:18.0.0@aar
+--- com.google.android.gms:play-services-basement:17.3.0@aar
+--- com.google.android.material:material:1.2.1@aar
+--- androidx.viewpager2:viewpager2:1.0.0@aar
+--- androidx.recyclerview:recyclerview:1.1.0@aar
+--- androidx.constraintlayout:constraintlayout:2.0.3@aar
+--- androidx.appcompat:appcompat:1.2.0@aar
+--- androidx.fragment:fragment:1.2.5@aar
+--- androidx.coordinatorlayout:coordinatorlayout:1.1.0@aar
+--- androidx.transition:transition:1.2.0@aar
+--- androidx.appcompat:appcompat-resources:1.2.0@aar
+--- androidx.vectordrawable:vectordrawable-animated:1.1.0@aar
+--- androidx.vectordrawable:vectordrawable:1.1.0@aar
+--- androidx.browser:browser:1.2.0@aar
+--- androidx.drawerlayout:drawerlayout:1.0.0@aar
+--- androidx.legacy:legacy-support-core-utils:1.0.0@aar
+--- androidx.loader:loader:1.0.0@aar
+--- androidx.viewpager:viewpager:1.0.0@aar
+--- androidx.customview:customview:1.0.0@aar
+--- androidx.activity:activity:1.1.0@aar
+--- androidx.core:core:1.3.2@aar
+--- androidx.versionedparcelable:versionedparcelable:1.1.0@aar
+--- androidx.collection:collection:1.1.0@jar
+--- androidx.cardview:cardview:1.0.0@aar
+--- com.google.firebase:firebase-components:16.0.0@aar
+--- androidx.cursoradapter:cursoradapter:1.0.0@aar
+--- androidx.lifecycle:lifecycle-runtime:2.3.0-beta01@aar
+--- androidx.lifecycle:lifecycle-viewmodel-savedstate:2.2.0@aar
+--- androidx.lifecycle:lifecycle-viewmodel:2.2.0@aar
+--- com.google.android.datatransport:transport-backend-cct:2.3.1@aar
+--- com.google.android.datatransport:transport-runtime:2.2.4@aar
+--- com.google.android.datatransport:transport-api:2.2.1@aar
+--- com.google.firebase:firebase-encoders-json:17.0.0@aar
+--- androidx.lifecycle:lifecycle-common-java8:2.2.0@jar
+--- androidx.lifecycle:lifecycle-livedata:2.2.0@aar
+--- androidx.lifecycle:lifecycle-livedata-core:2.2.0@aar
+--- androidx.savedstate:savedstate:1.0.0@aar
+--- androidx.lifecycle:lifecycle-common:2.3.0-beta01@jar
+--- androidx.room:room-runtime:2.2.5@aar
+--- androidx.arch.core:core-runtime:2.1.0@aar
+--- androidx.arch.core:core-common:2.1.0@jar
+--- androidx.room:room-common:2.2.5@jar
+--- androidx.localbroadcastmanager:localbroadcastmanager:1.0.0@aar
+--- com.google.firebase:firebase-encoders:16.0.0@jar
+--- androidx.interpolator:interpolator:1.0.0@aar
+--- androidx.sqlite:sqlite-framework:2.0.1@aar
+--- androidx.sqlite:sqlite:2.0.1@aar
+--- androidx.documentfile:documentfile:1.0.0@aar
+--- androidx.print:print:1.0.0@aar
+--- androidx.annotation:annotation:1.1.0@jar
+--- com.android.support:support-annotations:27.1.1@jar
+--- org.threeten:threetenbp:1.5.0:no-tzdb@jar
+--- com.google.firebase:protolite-well-known-types:17.1.0@aar
+--- io.grpc:grpc-protobuf-lite:1.28.0@jar
+--- com.google.protobuf:protobuf-javalite:3.11.0@jar
+--- io.grpc:grpc-android:1.28.0@aar
+--- io.grpc:grpc-core:1.28.0@jar
+--- io.grpc:grpc-stub:1.28.0@jar
+--- io.grpc:grpc-api:1.28.0@jar
+--- io.grpc:grpc-context:1.28.0@jar
+--- com.google.errorprone:error_prone_annotations:2.3.4@jar
+--- io.perfmark:perfmark-api:0.19.0@jar
+--- com.google.code.findbugs:jsr305:3.0.2@jar
+--- org.codehaus.mojo:animal-sniffer-annotations:1.18@jar
+--- com.google.guava:guava:28.1-android@jar
+--- com.google.guava:failureaccess:1.0.1@jar
+--- org.checkerframework:checker-compat-qual:2.5.5@jar
+--- com.google.j2objc:j2objc-annotations:1.3@jar
+--- com.google.code.gson:gson:2.8.6@jar
+--- com.google.android:annotations:4.1.1.4@jar
+--- com.google.dagger:dagger:2.27@jar
+--- javax.inject:javax.inject:1@jar
+--- com.adobe.marketing.mobile:assurance:1.0.0@aar
+--- com.adobe.marketing.mobile:mobileservices:1.1.2@aar
+--- com.adobe.marketing.mobile:analytics:1.2.6@aar
+--- com.adobe.marketing.mobile:userprofile:1.1.0@aar
+--- com.adobe.marketing.mobile:signal:1.0.3@aar
+--- com.adobe.marketing.mobile:identity:1.2.1@aar
+--- com.adobe.marketing.mobile:lifecycle:1.0.6@aar
+--- com.adobe.marketing.mobile:core:1.5.7@aar
+--- com.adjust.sdk:adjust-android:4.22.0@jar
+--- com.android.installreferrer:installreferrer:2.1@aar
+--- androidx.constraintlayout:constraintlayout-solver:2.0.3@jar
+--- androidx.annotation:annotation-experimental:1.0.0@aar
+--- nl.dionsegijn:konfetti:1.2.5@aar
+--- com.github.chrisbanes:PhotoView:2.3.0@aar
\--- com.squareup.leakcanary:shark-log:2.5@jar
+--- androidx.lifecycle:lifecycle-livedata-ktx:2.2.0@aar
+--- io.github.reactivecircus.flowbinding:flowbinding-android:1.0.0-beta01@aar
+--- io.github.reactivecircus.flowbinding:flowbinding-lifecycle:1.0.0-beta01@aar
+--- io.github.reactivecircus.flowbinding:flowbinding-common:1.0.0-beta01@aar
+--- org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.4.0@jar
+--- org.jetbrains.kotlin:kotlin-android-extensions-runtime:1.4.10@jar
+--- org.jetbrains.kotlin:kotlin-reflect:1.4.10@jar
+--- com.squareup.leakcanary:leakcanary-android-core:2.5@aar
+--- com.squareup.leakcanary:plumber-android:2.5@aar
+--- com.google.firebase:firebase-firestore-ktx:22.0.0@aar
+--- com.google.firebase:firebase-dynamic-links-ktx:19.1.1@aar
+--- com.google.firebase:firebase-crashlytics-ktx:17.2.2@aar
+--- com.google.firebase:firebase-common-ktx:19.3.1@aar
+--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.4.10@jar
+--- com.google.firebase:firebase-perf:19.0.9@aar
+--- com.google.firebase:firebase-functions:19.1.0@aar
+--- com.google.firebase:firebase-crashlytics:17.2.2@aar
+--- com.squareup.okhttp3:okhttp:4.9.0@jar
+--- androidx.core:core-ktx:1.3.2@aar
+--- org.jetbrains.anko:anko-commons:0.10.8@aar
+--- com.squareup.leakcanary:leakcanary-object-watcher-android-androidx:2.5@aar
+--- com.squareup.leakcanary:leakcanary-object-watcher-android-support-fragments:2.5@aar
+--- com.squareup.leakcanary:leakcanary-object-watcher-android:2.5@aar
+--- com.airbnb.android:lottie:3.4.4@aar
+--- com.squareup.moshi:moshi:1.11.0@jar
+--- com.google.firebase:firebase-firestore:22.0.0@aar
+--- io.grpc:grpc-okhttp:1.28.0@jar
+--- com.squareup.okhttp:okhttp:2.7.5@jar
+--- com.squareup.okio:okio:2.9.0@jar
+--- androidx.collection:collection-ktx:1.1.0@jar
+--- androidx.lifecycle:lifecycle-livedata-core-ktx:2.2.0@aar
+--- org.jetbrains.anko:commons-base:0.10.8@aar
+--- org.jetbrains.kotlin:kotlin-stdlib:1.4.10@jar
+--- org.jetbrains.kotlin:kotlin-stdlib-common:1.4.10@jar
+--- org.jetbrains:annotations:13.0@jar
```

**Comment by rd-martin-jaeger** [comment]
Could fix it by setting `android.enableJetifier=true` - which is dont like to be forced to.
Would be nice if you could upgrade your internal depedencies to androidx instead of using the old support libs.

Can be closed

**Comment by PravinPK** [comment]
Hi @rd-martin-jaeger,
  Glad you were able to get it fixed. We are still supporting the use of support libraries in order to maintain backward compatibility for Android apps that haven’t migrated to AndroidX yet. 
We are keeping an eye on any Android announcements and evaluating the time to migrate our libraries to Android X. Stay tuned.

Thanks,
Pravin
