### ISSUE TITLE
Android memory leaks

### ISSUE THREAD

**Issue by mortenholmgaard** [Adobe-Marketing-Cloud/acp-sdks#537]
I get leaks logged all the time using those versions when running leakcanary to detect leaks:

    implementation 'com.adobe.marketing.mobile:analytics:1.2.6'
    implementation 'com.adobe.marketing.mobile:userprofile:1.1.0'
    implementation 'com.adobe.marketing.mobile:sdk-core:1.5.8'
    implementation 'com.adobe.marketing.mobile:mobileservices:1.1.2'
    implementation 'com.adobe.marketing.mobile:target:1.1.6'

Please fix this.
```
A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
    java.lang.Throwable: Explicit termination method 'end' not called
        at dalvik.system.CloseGuard.open(CloseGuard.java:223)
        at java.util.zip.Inflater.<init>(Inflater.java:106)
        at com.android.okhttp.okio.GzipSource.<init>(GzipSource.java:62)
        at com.android.okhttp.internal.http.HttpEngine.unzip(HttpEngine.java:473)
        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:648)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:471)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(Unknown Source:0)
        at com.adobe.marketing.mobile.AndroidHttpConnection.getResponseCode(AndroidHttpConnection.java:70)
        at com.adobe.marketing.mobile.TargetExtension.processTargetRequestResponse(TargetExtension.java:1084)
        at com.adobe.marketing.mobile.TargetExtension.batchRequests(TargetExtension.java:1048)
        at com.adobe.marketing.mobile.TargetExtension.access$100(TargetExtension.java:32)
        at com.adobe.marketing.mobile.TargetExtension$1.run(TargetExtension.java:149)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by rymorale** [comment]
Hi @mortenholmgaard, there have been some fixes made in Android ACP Core 1.6.0 related to the Android `okhttp` library. Could you give the latest Android core build a try to see if you are still experiencing the issue?

Thanks,
Ryan Morales
Mobile Engineer
[Adobe Experience Cloud](https://www.adobe.com/experience-cloud.html)

**Comment by mortenholmgaard** [comment]
@rymorale I have now testet with `implementation 'com.adobe.marketing.mobile:sdk-core:1.7.0'` and the problem still exists!

**Comment by rymorale** [comment]
Thanks for giving it a try @mortenholmgaard. We will investigate this further and let you know more after.

**Comment by mortenholmgaard** [comment]
Sorry missed your questions.
>what android device are you seeing the leak on? do you see the leak issue on multiple android devices or is it only occurring on one device?
Nexus 5X Android 27, I haven't testet that on other devices.

>does the leak occur with earlier versions of the ACP SDK?
Don't know, havent tried.

>does the leak occur with other ACP SDK API or only with the Target API?
I have only seen it with Target API.

>does your app's other HTTP requests have a similar leak?
No

**Comment by mortenholmgaard** [comment]
@rymorale Any news on this?

**Comment by rymorale** [comment]
Hi @mortenholmgaard, could you try an earlier version of the ACP SDK (Core and Target specifically)?

**Comment by addb** [comment]
@mortenholmgaard Were you able to resolve this issue? If you still need help with this issue, please open a ticket with our [Client Support Team](https://experienceleague.adobe.com/?support-solution=General#support)
