### ISSUE TITLE
Android 12 Pending intents mutability Crash

### ISSUE THREAD

**Issue by diogo-martins-engineer** [Adobe-Marketing-Cloud/acp-sdks#616]
Getting the following crash (with Places Monitor) on apps that target Android 12.

`Fatal Exception: java.lang.IllegalArgumentException: pt.viaverde.clientes: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
       at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
       at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
       at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
       at com.adobe.marketing.mobile.PlacesLocationManager.getPendingIntent(PlacesLocationManager.java:375)
       at com.adobe.marketing.mobile.PlacesLocationManager.stopLocationUpdates(PlacesLocationManager.java:326)
       at com.adobe.marketing.mobile.PlacesLocationManager.stopMonitoring(PlacesLocationManager.java:206)
       at com.adobe.marketing.mobile.PlacesMonitorInternal.stopMonitoring(PlacesMonitorInternal.java:465)
       at com.adobe.marketing.mobile.PlacesMonitorInternal.processMonitorRequestEvent(PlacesMonitorInternal.java:279)
       at com.adobe.marketing.mobile.PlacesMonitorInternal.processEvents(PlacesMonitorInternal.java:242)
       at com.adobe.marketing.mobile.PlacesMonitorListenerMonitorRequestContent$1.run(PlacesMonitorListenerMonitorRequestContent.java:73)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:920)`

The sdk's PendingIntens must be updated https://developer.android.com/about/versions/12/behavior-changes-12#pending-intent-mutability

**Comment by PravinPK** [comment]
Hi @diogo-martins-engineer,

I am sorry to announce that the Places Monitor extension for the Adobe Experience Platform Mobile SDKs is deprecated as of August 31st 2021. The extension will not receive further updates or support from Adobe.

An ideal solution for you would be to fork the [Places Monitor](https://github.com/adobe/places-monitor-android) repository, make the required changes and add the library's build manually to your application. Let me know if you need any assistance.


Thanks,
Pravin

**Comment by PravinPK** [comment]
Hi @diogo-martins-engineer, 
A new version of PlacesMonitor (2.2.3) was released supporting Android 12.

Thanks,
Pravin
