### ISSUE TITLE
[Android Issue] - Package manager has died

### ISSUE THREAD

**Issue by badariadda** [Adobe-Marketing-Cloud/acp-sdks#665]
Fatal Exception: java.lang.RuntimeException: Package manager has died
       at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:320)
       at com.adobe.marketing.mobile.AndroidSystemInfoService.l(AndroidSystemInfoService.java:3)
       at com.adobe.marketing.mobile.LifecycleMetricsBuilder.a(LifecycleMetricsBuilder.java:10)
       at com.adobe.marketing.mobile.LifecycleListenerHubBooted$1.run(LifecycleListenerHubBooted.java:6)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
Caused by android.os.DeadObjectException
       at android.os.BinderProxy.transactNative(Binder.java)
       at android.os.BinderProxy.transact(Binder.java:503)
       at android.content.pm.IPackageManager$Stub$Proxy.getApplicationInfo(IPackageManager.java:2405)
       at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:292)
       at com.adobe.marketing.mobile.AndroidSystemInfoService.l(AndroidSystemInfoService.java:3)
       at com.adobe.marketing.mobile.LifecycleMetricsBuilder.a(LifecycleMetricsBuilder.java:10)
       at com.adobe.marketing.mobile.LifecycleListenerHubBooted$1.run(LifecycleListenerHubBooted.java:6)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)

Device
Brand:BlackBerry
Model:DTEK60
Orientation: Portrait
RAM free: Unknown
Disk free: 4.83 GB
Operating System
Version:Android 6.0.1
Orientation: Portrait
Rooted:No

**Comment by praveek** [comment]
@badariadda We have added some additional checks to prevent the crash in Core v1.11.2.
